### ISSUE TITLE
Does not join to the domain

### ISSUE THREAD

**Issue by jasoncal108** [lae/ansible-role-system_ldap#2]
I've tried to use the playbook role, but have not been successful.  It appears that it updates config files, but I don't see anywhere it performing a 'net ads join'. How exactly is this supposed to join a domain without those commands?

**Comment by lae** [comment]
This role doesn't join servers to a domain - it only configures SSSD as an authentication endpoint for PAM (e.g. for logging in via SSH or a TTY with an LDAP account).
