### ISSUE TITLE
case_sensitive

### ISSUE THREAD

**Issue by Poil** [lae/ansible-role-system_ldap#4]
Hi,

In most case Login is case insensitive, we should allow to configure ```case_sensitive = False``` in  templates/sssd.conf.j2 and downcase user and group in templates/ldap_sudo*

Best regards,

**Comment by lae** [comment]
I think this is already implemented as default? See https://github.com/lae/ansible-role-system_ldap/commit/5280b7f3f749fec2f6165af65fc0a89309269bd9

As for templates, up until now I guess I've been expecting users only input downcased usernames in `system_ldap_sudo_users` - are you just asking it to be enforced?

**Comment by lae** [comment]
Closing due to no response. Please reopen with clarification if you need to.
